name: Build Comic
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-mock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Run agent (mock or CPU)
        run: |
          python -c "import os; os.makedirs('out/pages',exist_ok=True); os.makedirs('out/panels',exist_ok=True)"
          python -m src.agent --scene prompts/example_scene.json --policy configs/policy.json --chars configs/characters.json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: comic-output
          path: out/
          if-no-files-found: warn
